config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :test_suites, :only => [:index, :show] do
    resources :test_cases, :only => [:show] do
      resources :test_case_runs, :only => [:index, :show]
    end
    resources :test_suite_runs, :only => [:index, :show]
  end

  resources :users, :only => [:show]
  resources :issues

  # Custom Routes
  get   "login"  => "sessions#new", :as => :login
  post  "login"  => "sessions#create"
  match "logout" => "sessions#destroy", :as => :logout, :via => [:get, :delete]

  get 'test_suites/:id/run' => "test_suites#run", :as => :run_test_suite
  get 'test_suites/:id/last_20_runs' => "test_suite_runs#last_20_runs"

  get 'profile' => "users#show", :as => :profile

  # Default Route
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :test_suite

  def self.active_issues
    self.where(:active => true)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :test_suite
end

app/models/notification_profile.rb
class NotificationProfile < ApplicationRecord
  belongs_to :user
end

app/models/test_case.rb
class TestCase < ApplicationRecord
  belongs_to :test_suite

  has_many :test_case_runs

  def passing_rate
    test_case_runs = TestCaseRun.where(:test_case_id => self.id)

    count = test_case_runs.count
    passing = test_case_runs.where(:status => 1).count

    ((100 * passing) / count.to_f).round(2)
  end

  def average_time
    test_case_runs = TestCaseRun.where(:test_case_id => self.id)

    test_case_runs.average(:time).round(2)
  end
end

app/models/test_case_run.rb
class TestCaseRun < ApplicationRecord
  belongs_to :test_case
  belongs_to :test_suite_run
end

app/models/test_suite.rb
class TestSuite < ApplicationRecord
  has_many :test_suite_runs
  has_many :test_cases
  has_many :issues
end

app/models/test_suite_run.rb
class TestSuiteRun < ApplicationRecord
  belongs_to :test_suite
  has_many :test_case_runs

  def passed?
    if failures + errs == 0
      true
    else
      false
    end
  end

  def css_mapping
    self.passed? ? "table-success" : "table-danger"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :notification_profile, :dependent => :destroy
  has_many :notifications, :dependent => :destroy

  accepts_nested_attributes_for :notification_profile, :notifications

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, RakeTestHelper

  protected

  def authenticate!
    redirect_to login_path unless warden.authenticated?
  end

  def current_user
    warden.user
  end

  def warden
    request.env["warden"]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate!

  def index
    @test_suites = TestSuite.includes(:test_suite_runs)
    @issues = Issue.active_issues
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:update]

  def index
    @issues = Issue.where(:active => true)
  end

  def update
    if @issue.update!(issue_params)
      redirect_to issues_path, notice: 'Issue has been successfully updated.'
    end
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:active)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ::ApplicationController
  # GET /login
  def new
    flash[:error] = warden.message if warden.message
  end

  # POST /login
  def create
    warden.authenticate!(:ldap)
    flash.clear

    redirect_to root_path
  end

  # GET /logout
  def destroy
    warden.logout
    redirect_to login_path
  end
end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  before_action :set_test_case, only: []

  # GET /test_cases/1
  # GET /test_cases/1.json
  def show
    @test_case = TestCase.includes(:test_case_runs => :test_suite_run).find(params[:id])

    @passing_rate = calculate_passing_rate
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_case
      @test_case = TestCase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_case_params
      params.fetch(:test_case, {})
    end

    def calculate_passing_rate
      ((@test_case.test_case_runs.where(:status => 1).count/@test_case.test_case_runs.count.to_f)*100).round(2)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :authenticate!

  def show
    @user = User.find(current_user)

    if @user.notification_profile.nil?
      @user.create_notification_profile
    end

    initialize_notifications(@user)
  end

  def update
    respond_to do |format|
      if @user.update!(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to @user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def initialize_notifications(user)
      TestSuite.all.each do |test_suite|
        user.notifications.where(:test_suite_id => test_suite.id).first_or_initialize
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(notification_profile_attributes: [:id, :slack_enabled, :slack, :email_enabled, :email, :sms_enabled, :sms], notifications_attributes: [:id, :slack, :email, :sms, :test_suite_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/test_case_runs_helper.rb
module TestCaseRunsHelper
end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/helpers/test_suite_runs_helper.rb
module TestSuiteRunsHelper
end

app/helpers/test_suites_helper.rb
module TestSuitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/index.html.erb
<p id="notice"></p>

<div class="container">
  <% if @issues.blank? %>
    <div class="row">
      <div class="col-md-12 text-sm-center">
        <h1> No Issues! :)</h1>
      </div>
    </div>
  <% else %>
    <% @issues.each do |issue| %>
      <div class="row">
        <div class="card">
          <div class="card-block">
            <h4 class="card-title"><%= link_to issue.test_suite.name, test_suite_test_suite_runs_path(issue.test_suite.id) %></h4>
            <div class="col-md-6">
              <h6>Last Occured: <%= "#{time_ago_in_words(issue.updated_at)} ago" %></h6>
              <h6>First Occured: <%= "#{time_ago_in_words(issue.created_at)} ago" %></h6>
            </div>
            <div class="col-md-4 text-sm-center">
              <h6>Occurences</h6>
              <%= issue.num_of_occurences %>
            </div>
            <div class="col-md-2">
              <%= form_for issue do |f| %>
                <%= f.hidden_field :active, :value => false %>
                <%= submit_tag("Acknowledge", :class => 'btn btn-primary') %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.fields_for :notification_profile do |npf| %>

    <div class="form-group row">
      <%= npf.label :slack, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= npf.text_field(:slack ,:class => "form-control", :placeholder => "@username") %>
      </div>
    </div>

    <div class="form-group row">
      <%= npf.label :email, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= npf.text_field(:email ,:class => "form-control", :placeholder => "dobby@mx.com") %>
      </div>
    </div>

    <div class="form-group row">
      <%= npf.label :sms, :class => "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= npf.text_field(:sms ,:class => "form-control", :placeholder => "801-867-5309") %>
      </div>
    </div>

    <div class="form-group row">
      <table class="table">
        <tr>
          <th>Test Suite</th>
          <th class='text-sm-center'>Slack</th>
          <th class='text-sm-center'>Email</th>
          <th class='text-sm-center'>SMS</th>
        </tr>
        <%= f.fields_for :notifications do |n| %>
          <tr>
            <%= n.hidden_field :test_suite_id %>
            <td><%= n.object.test_suite.name %></td>
            <td class='text-sm-center'><%= n.check_box(:slack) %></td>
            <td class='text-sm-center'><%= n.check_box(:email)%></td>
            <td class='text-sm-center'><%= n.check_box(:sms)%></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div> <!-- Bad div, escapes div outside of this partial. fix at some point -->
    <div class="card-footer text-sm-right">
      <%= submit_tag("Update", :class => 'btn btn-secondary') %>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-header text-sm-right">
        <%= link_to 'Logout', logout_path, :class => 'btn btn-primary' %>
      </div>
      <div class="card-block">
        <h4 class="card-title"><%= @user.full_name %></h4>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>