config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :test_suites, :only => [:index, :show] do
    resources :test_cases, :only => [:show] do
      resources :test_case_runs, :only => [:index, :show]
    end
    resources :test_suite_runs, :only => [:index, :show]
  end

  resources :users, :only => [:show]
  resources :issues

  # Custom Routes
  get   "login"  => "sessions#new", :as => :login
  post  "login"  => "sessions#create"
  match "logout" => "sessions#destroy", :as => :logout, :via => [:get, :delete]

  get 'test_suites/:id/run' => "test_suites#run", :as => :run_test_suite
  get 'test_suites/:id/last_20_runs' => "test_suite_runs#last_20_runs"

  get 'profile' => "users#show", :as => :profile

  # Default Route
  root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :test_suite

  def self.active_issues
    self.where(:active => true)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :test_suite
end

app/models/notification_profile.rb
class NotificationProfile < ApplicationRecord
  belongs_to :user
end

app/models/test_case.rb
class TestCase < ApplicationRecord
  belongs_to :test_suite

  has_many :test_case_runs

  def passing_rate
    test_case_runs = TestCaseRun.where(:test_case_id => self.id)

    count = test_case_runs.count
    passing = test_case_runs.where(:status => 1).count

    ((100 * passing) / count.to_f).round(2)
  end

  def average_time
    test_case_runs = TestCaseRun.where(:test_case_id => self.id)

    test_case_runs.average(:time).round(2)
  end
end

app/models/test_case_run.rb
class TestCaseRun < ApplicationRecord
  belongs_to :test_case
  belongs_to :test_suite_run
end

app/models/test_suite.rb
class TestSuite < ApplicationRecord
  has_many :test_suite_runs
  has_many :test_cases
  has_many :issues
end

app/models/test_suite_run.rb
class TestSuiteRun < ApplicationRecord
  belongs_to :test_suite
  has_many :test_case_runs

  def passed?
    if failures + errs == 0
      true
    else
      false
    end
  end

  def css_mapping
    self.passed? ? "table-success" : "table-danger"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :notification_profile, :dependent => :destroy
  has_many :notifications, :dependent => :destroy

  accepts_nested_attributes_for :notification_profile, :notifications

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:update]

  def index
    @issues = Issue.where(:active => true)
  end

  def update
    if @issue.update!(issue_params)
      redirect_to issues_path, notice: 'Issue has been successfully updated.'
    end
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:active)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ::ApplicationController
  # GET /login
  def new
    flash[:error] = warden.message if warden.message
  end

  # POST /login
  def create
    warden.authenticate!(:ldap)
    flash.clear

    redirect_to root_path
  end

  # GET /logout
  def destroy
    warden.logout
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :authenticate!

  def show
    @user = User.find(current_user)

    if @user.notification_profile.nil?
      @user.create_notification_profile
    end

    initialize_notifications(@user)
  end

  def update
    respond_to do |format|
      if @user.update!(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to @user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def initialize_notifications(user)
      TestSuite.all.each do |test_suite|
        user.notifications.where(:test_suite_id => test_suite.id).first_or_initialize
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(notification_profile_attributes: [:id, :slack_enabled, :slack, :email_enabled, :email, :sms_enabled, :sms], notifications_attributes: [:id, :slack, :email, :sms, :test_suite_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/test_case_runs_helper.rb
module TestCaseRunsHelper
end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/helpers/test_suite_runs_helper.rb
module TestSuiteRunsHelper
end

app/helpers/test_suites_helper.rb
module TestSuitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Frontage</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li class="text-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <%= link_to "Frontage", root_path, :class => "navbar-brand" %>
  <ul class="nav navbar-nav">
    <% if current_user %>
      <li class="nav-item">
        <%= link_to "Test Suites", test_suites_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Issues", issues_path, :class => "nav-link" %>
      </li>
      <li class="nav-item pull-xs-right">
        <%= link_to "Hello, #{current_user.first_name}", profile_path, :class => "nav-link" %>
      </li>
    <% end %>

  </ul>
</nav>

app/views/widgets/_issues.html.erb
<div class="container">
  <% if @issues.blank? %>
    <div class="row">
      <div class="col-md-12 text-sm-center">
        <h1> No Issues! :)</h1>
      </div>
    </div>
  <% else %>
    <% @issues.each do |issue| %>
      <div class="row">
        <div class="card issue">
          <div class="card-block">
            <h4 class="card-title"><%= link_to issue.test_suite.name, test_suite_path(issue.test_suite.id) %></h4>
            <div class="col-md-6">
              <h6>Last Occured: <%= "#{time_ago_in_words(issue.updated_at)} ago" %></h6>
              <h6>First Occured: <%= "#{time_ago_in_words(issue.created_at)} ago" %></h6>
            </div>
            <div class="col-md-4 text-sm-center">
              <h6>Occurences</h6>
              <%= issue.num_of_occurences %>
            </div>
            <div class="col-md-2">
              <%= form_for issue do |f| %>
                <%= f.hidden_field :active, :value => false %>
                <%= submit_tag("Acknowledge", :class => 'btn btn-primary') %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/widgets/_pass_fail_graph.html.erb
<div class="test-suite" test-suite-id="<%= test_suite_id %>">
  <div class="card-block">
    <div class="chart-<%= test_suite_id %>"></div>
  </div>
</div>

<script>
  graphs.dashboard(<%= test_suite_id %>);
</script>

app/views/widgets/_test_cases.html.erb
<div class="col-sm-12">
  <table class="table">
    <thead>
      <tr>
        <th class="text-sm-left">Name</th>
        <th class="text-sm-center">Passing Rate</th>
        <th class="text-sm-center">Average time to run</th>
      </tr>
    </thead>
    <tbody>
      <% @test_cases.each do |test_case| %>
        <tr class="text-sm-center">
          <td class="text-sm-left"><%= link_to test_case.name, test_suite_test_case_test_case_runs_path(params[:id], test_case.id) %></td>
          <td><%= test_case.passing_rate %>%</td>
          <td><%= test_case.average_time %>s</div>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row text-sm-right">
  </div>
</div>

app/views/widgets/_test_suite_runs.html.erb
<div class="col-sm-12">
  <table class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th># of Tests</th>
        <th>Failures</th>
        <th>Errors</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @test_suite_runs.each do |test_suite_run| %>
        <tr class="<%= test_suite_run.css_mapping %>">
          <td><%= time_ago_in_words(test_suite_run.timestamp) %> ago</td>
          <td><%= test_suite_run.tests %></td>
          <td><%= test_suite_run.failures %></td>
          <td><%= test_suite_run.errs %></td>
          <td><%= link_to 'Show', test_suite_test_suite_run_path(test_suite_run.test_suite_id, test_suite_run)  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row text-sm-right">
    <%= will_paginate @test_suite_runs %>
  </div>
</div>

app/views/widgets/_test_suites.html.erb
<div class="row">
  <% @test_suites.each do |test_suite| %>
    <% test_suite_run = test_suite.test_suite_runs.order(:id).last %>
    <div class="col-md-6">
      <div class="card test-suite" test-suite-id="<%= test_suite.id %>">
        <div class="card-block">
          <h4 class="card-title"><%= test_suite.name.titleize %></h4>
          <span class="text-muted"><%= test_suite.task_name %></span>
          <%= render partial: "widgets/pass_fail_graph", locals: {test_suite_id: test_suite.id} %>
          <%= link_to 'Show', test_suite_path(test_suite), :class => 'btn btn-primary' %>
          <%= link_to 'Run', run_test_suite_path(test_suite), :class => 'btn btn-primary' %>
        </div>
        <div class="card-footer text-muted">
          <div class="row">
            <div class="col-sm-12">
              Last Run
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <%= time_ago_in_words(test_suite_run.timestamp) %> ago
            </div>
            <div class="col-sm-6">
              <% if test_suite_run.passed? %>
              Passed
              <% else %>
              Failed
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>